### ISSUE TITLE
tablayout+viewpager 怎么处理

### ISSUE THREAD

**Issue by douya40** [lvtanxi/BaseVLayoutAdapterHelper#1]
tablayout+viewpager 怎么处理

**Comment by lvtanxi** [comment]
tablayout+viewpager ？能具体说明下情况不呢？

**Comment by lvtanxi** [comment]
tablayout+viewpager ？能说明具体问题不呢

**Comment by douya40** [comment]
tablayout+viewpager 使用vlayout怎么实现呢

**Comment by lvtanxi** [comment]
tablayout与viewpager好像与vlayout没什么关系吧？如果你想知道tablayout与viewpager怎么联合使用可以看看这个：http://www.jianshu.com/p/adf7a994613a

**Comment by douya40** [comment]
tablayout+viewpager套在vlayout，我套的显示有问题

**Comment by lvtanxi** [comment]
你可以贴出错误信息，这样才好做出相应的解决方案

**Comment by douya40** [comment]
方便留个QQ我单线联系你妈

**Comment by lvtanxi** [comment]
992507862
